### ISSUE TITLE
Siphon out SymEngine 

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/ParameterizedFunctions.jl#14]
I think it would be good to separate the parsing / defining core of ParameterizedFunctions.jl from the symbolic calculation add-on of SymEngine. One reason for this is that many people seem to have build issues with SymEngine, so this would be able to make these extra enhancements optional to DifferentialEquations.jl without the full removal of ParameterizedFunctions.jl, and it would allow for very small builds which will help with the DiffEqOnline web deployment.

The implementation is pretty simple: move out this try/catch block

https://github.com/JuliaDiffEq/ParameterizedFunctions.jl/blob/master/src/ode_def_opts.jl#L80

However, it means that the macros which use this functionality will break. @tkelman, would it be okay to not have that library as a requirement (due to the build/size issues), have these extra macros broken, and throw an error telling the user to install some ParameterizedFunctionsSymEngine.jl to use them? Or is that not considered good form?

**Comment by tkelman** [comment]
The macros should be defined in the combination package, not here, if they need the dependency to be present to work. Otherwise you'll have to put flaky conditional checking here.
