### ISSUE TITLE
DAEProblem compatibility

### ISSUE THREAD

**Issue by gbenham** [JuliaDiffEq/ParameterizedFunctions.jl#16]
Hi there,

ParameterizedFunction.jl does not currently work in conjunction with differential algebraic equations using DAEProblem from DifferentialEquations.jl.

Please could we make this possible?

(this was already mentioned in https://github.com/JuliaDiffEq/ParameterizedFunctions.jl/issues/5)

Thanks, 
Graham

**Comment by ChrisRackauckas** [comment]
Added on master

http://docs.juliadiffeq.org/latest/analysis/parameterized_functions.html#ParameterizedFunction-Constructor-1
