### ISSUE TITLE
ParameterizedFunctions syntax overhaul bikeshedding

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/ParameterizedFunctions.jl#17]
ParameterizedFunctions.jl's `@ode_def` DSL needs a slight overhaul. Specifically, I would like to see if a nice syntax can make it handle differential-algebraic equations, delay differential equations, higher order differential equations, intermediate computations, internal functions, order reduction of DAEs, etc. If we are capable, having it describe PDEs would be amazing as well. Essentially, something that can take a very general looking "ODE", and make it spit out something to solve. 

This would handle issues https://github.com/JuliaDiffEq/ParameterizedFunctions.jl/issues/5, https://github.com/JuliaDiffEq/ParameterizedFunctions.jl/issues/11, and others which haven't been written down.

The question is, what is a syntax which is easy for humans to understand, but is easily parsable to equation types? That is the first step. Making use of this representation to do all of the more advanced behavior can come later, but first we just need a parsable syntax.

My first proposal is something like this:

Let `x'` stand for the derivative. `x''` etc. stand for higher order derivatives. We'll leave it open for now how to do nth order derivatives in an easier way.

Let `x` and `x'` alias for `x(t)` and `x'(t)`. The first job in parsing would be to do this conversion.

So then the general equation has `x(t)` for dependent variables, and the independent variable defaults to `t`. There should be a way for the user to change the symbol for the independent variable, or make it a tuple of symbols for multiple independent variables (for PDEs).

For describing PDEs, `x'` will default to being the derivative of the first variable. But more generally, derivatives would be written as `x_t` for a single derivative, or `x_tt` etc. for more. Again, this parses to `x_t(t)`. Later we can add special operators like `Δ` which expands to `u_xx + u_yy + ...` using all of the not first dependent variable (first is always assumed to be time).

So for ODEs we would have `x'` -> `x'(t)` -> `x_t(t)` as the internal form. This should work for PDEs? This also lets one specify delays, since would could directly write `x'(t-2)`, or `x'(t-y')` to go more generally. 

An example would look like:

```julia
f = @ode_def LotkaVolterra begin
  x' = a*x - b*x*y
  y' = -c*y + d*x*y
end a=>1.5 b=>1 c=3 d=1
```

for something basic, or one could write the DAE

```julia
f = @ode_def LotkaVolterra begin
  x' + y' = a*x - b*x*y
  y' = -c*y + d*x*y
end a=>1.5 b=>1 c=3 d=1
```

or one could write the neutral delay equation

```julia
f = @ode_def LotkaVolterra begin
  x' + y' = a*x(t-y') - b*x*y
  y' = -c*y + d*x*y
end a=>1.5 b=>1 c=3 d=1
```

However, the question to answer is, **can this actually be unambiguously parsed?**

First of all, how does one determine the dependent variables? By not allowing DAEs in the previous version of the macro, I could just assume that the dependent variables would be known by checking the left-and side. However, with DAEs, the formulation

```julia
f = @ode_def LotkaVolterra begin
  0 = - x' - y' + a*x(t-y') - b*x*y
  y' = -c*y + d*x*y
end a=>1.5 b=>1 c=3 d=1
```

is perfectly valid. Also, for DAEs, not every term has to have a derivative term, so is it possible to parse out what the independent variables are supposed to be? Also, is the `x_t` form easy to parse, or would that cause a lot of potential problems? It can only `_` then do some finite number of the dependent variables, so that seems doable. 

I would like some input on others for what a good syntax would be. I'm happy to give example equations if one would like to have a few to think about.

**Comment by ChrisRackauckas** [comment]
Pinging @pwl @mauro3 @gabrielgellner @Armavica @elevien @ScottPJones as people I know help with bikeshedding 👍

**Comment by ChrisRackauckas** [comment]
Oh, and one last thing I have been thinking about is not having it directly return the function. Rather, have it return some kind of type which holds all of the information for some functions, and create dispatches for the `Problem` types to then use the function. This would allow us to create a `identity_problem_type(f)` and `DiffEqProblem(f,u0,tspan)` (or replace tspan by a mesh for multiple dependent variables) so that way, it can on its own "create the best problem type" given what it's parsed. For example, that way one could have this parse a higher order DAE, and it can perform order reduction to build an equivalent order-1 DAE, which will make a `DAEProblem` to solve. This would allow for machinery to make setting up the solvers for DEs and the associated conversions seem automatic and magical.

**Comment by mauro3** [comment]
Is there no desire to keep `'` available as adjoint?  I think the `x_t` syntax is fine.  Also, optionally one could use `xₜ` or `uₓₓ` if pretty is important.

**Comment by tshort** [comment]
I like the idea of returning a type. That may open up options for interesting manipulation. An area of interest of mine is the ability to compose a set of equations from reusable parts. Your syntax is starting to look tantalizingly close to what I was aiming for with [Sims.jl](http://tshort.github.io/Sims.jl/stable/).  It would be great to be able to compose smaller parts into a set of equations.

Other things to think about are:
* Indicating and handling complex numbers
* Defining sets of equations

Also, did you mean to have all of them defined with the same `@ode_def`? Or do we need `@dae_def` or `@dde_def` as needed?

**Comment by ChrisRackauckas** [comment]
>Is there no desire to keep ' available as adjoint? I think the x_t syntax is fine. Also, optionally one could use xₜ or uₓₓ if pretty is important.

I really like that. Okay, no `'`, just `x_t` or the Unicode version. I can get behind that.

>Indicating and handling complex numbers

In DiffEq this is always handled by the input type. If the initial condition is an array of complex numbers, then the variables are complex. I like that setup because it ensures type-stability. Is there anything that can be gained by declaring something is complex at this stage?

>Also, did you mean to have all of them defined with the same @ode_def? Or do we need @dae_def or @dde_def as needed?

Yeah. The way I am thinking about it is: the delay equation method would need to be able to find out what the delays are. But if the delays are trivial, it can determine that it doesn't have delays. Similarly for DAEs, it needs to determine what the purely algebraic variables are. But if it can do that, it can detect that there are no algebraic variables, and thus determine that it's not a DAE. So it seems that if the parser can effectively make the DAEs and DDEs, then it can already detect when it's an ODE, meaning they can all be the same macro. At least I think that makes sense.

>It would be great to be able to compose smaller parts into a set of equations.

That would be cool. And a type for this would allow that.

>Your syntax is starting to look tantalizingly close to what I was aiming for with Sims.jl.

Maybe we should make sure it's cross compatible. I think we are heading in a similar direction in terms of designing DSLs. Another DSL which is looking similar is the chemical kinetics

http://tshort.github.io/Sims.jl/stable/lib/kinetics.html
https://github.com/JuliaDiffEq/DiffEqBiological.jl/issues/2

**Comment by mauro3** [comment]
Sadly, not all letters can turn into subscripts, in particular `u\_y` and `u\_z` don't.  See https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts#Latin_and_Greek_tables

**Comment by ChrisRackauckas** [comment]
>Sadly, not all letters can turn into subscripts, in particular u\_y and u\_z don't. See https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts#Latin_and_Greek_tables

Might as well accept the ones that do though. This is another reason to be pro for that proposal to the Unicode Consortium people together by the Julia folks.

**Comment by Armavica** [comment]
I would really like to be able to write something like `u_x` for `du/dx`. Unfortunately I can see several problems with this. Some thoughts:

## Multiple derivatives

 If we write `u_xy` for `du/(dxdy)`, then how should we write `du/dxy` (derivative with respect to the variable `xy`)? Preventing independent variables to be more than one character is probably not an option (or is it?).

A solution would be to write `du/(dxdy)` as `u_x_y`, which leaves `u_xy` for `du/dxy`.
 But then, this seems to forbid any dependent, or independent variable to contain a `_`. I find this more reasonable, although not entirely satisfactory. Maybe some sort of variable declaration could be helpful? We could ask to specify the lists of dependent variables, and independent variables.

## Delays and taking values at different points

> So for ODEs we would have `x'` -> `x'(t)` -> `x_t(t)` as the internal form. This should work for PDEs? This also lets one specify delays, since would could directly write `x'(t-2)`, or `x'(t-y')` to go more generally.

I am wondering how to be even more general. How would you write, for example, `u(t-tau, a*x)` (I actually work on systems of this form)? I find it neat to be able to omit the list of independent variables in more classic situations, but let's not forget that delays and such can be in other variables than time.

## Sugar

Do we want sugar for `d(x*u(x))/dx`, or `d(u(x)*v(x))/dx` for example? Something like `(x*u)_x` and `(u*v)_x` maybe?

## Integro-differential equations

I can still dream, right? ;)

Sorry, this post has more questions than answers. I will try to think more about this problem.

**Comment by ChrisRackauckas** [comment]
>Preventing independent variables to be more than one character is probably not an option (or is it?)

That is an option.

>Maybe some sort of variable declaration could be helpful?

Maybe. I liked that it was automatic, but maybe it is necessary. However, a variable declaration could be a source of errors, so I'd like to avoid it if possible.

>How would you write, for example, u(t-tau, a*x)

Like that. If there's one independent variable, it's `u(t)`. If there's two, it's `u(t,x)`, etc., matching the symbols for the independent variables.

>Do we want sugar for d(x*u(x))/dx, or d(u(x)*v(x))/dx for example? Something like (x*u)_x and (u*v)_x maybe?

That sounds like a great idea. I see Burger's equation coming out there. 

>Integro-differential equations

Integro-differential equations are fine. We have delay differential equation solvers with unconstrained stepping, so one way to already solve them is to write the integral as a quadrature. But another popular way is to transform into a DAE. So instead of requiring that they are written as a quadrature, we should have a way to specify and recognize IDEs, and let one build a DAE or DDE from it (a good reason to return a type). 

Would keeping `Int(low,high,integrand)` as a special syntax (aliased to `∫(low,high,integrand)` for sugar) be a good idea?

**Comment by mauro3** [comment]
I think a 80-90% solution is what you should aim for.  So, for example, maybe single letter variables would be fine.

**Comment by Armavica** [comment]
> However, a variable declaration could be a source of errors, so I'd like to avoid it if possible.

I would argue the opposite: without declarations, if you mistype a variable and accidentally introduce a new one, the solver will try to solve the incorrect system, whereas a declaration would have caught the error.

> If there's one independent variable, it's u(t). If there's two, it's u(t,x), etc., matching the symbols for the independent variables.

How do you define the order of the parameters? (How do you know if `u(t, 2, 3)` means `u(t, x=2, y=3)` or `u(t, y=2, x=3)`?)

> Would keeping Int(low,high,integrand) as a special syntax (aliased to ∫(low,high,integrand) for sugar) be a good idea?

What about the integration variable? Maybe `Int(integrand, variable, low, high)` is a bit more standard? (You asked for bikeshedding, right? ;)

> I think a 80-90% solution is what you should aim for. So, for example, maybe single letter variables would be fine.

I agree. Maybe we could authorize a number after the letter though? It leaves parsing unambiguous and allows variables like `x1`, `x2`, `x3`, etc.

**Comment by ChrisRackauckas** [comment]
>How do you define the order of the parameters? (How do you know if u(t, 2, 3) means u(t, x=2, y=3) or u(t, y=2, x=3)?)

I would say that, for dependent variables, the ordering matches the ordering of the independent variables, which are determined by some `dependent_vars = (:t,:x,:y)`.

>I agree. Maybe we could authorize a number after the letter though? It leaves parsing unambiguous and allows variables like x1, x2, x3, etc.

I think that could work. One letter plus numbers can be enforced, and that should make most parsing unambiguous unless someone has some insanely crazy name, in which case that's their problem.

>What about the integration variable? Maybe Int(integrand, variable, low, high) is a bit more standard? (You asked for bikeshedding, right? ;)

Yes, forgot about the variable. Yup, this is why I asked for help 👍 

>I think a 80-90% solution is what you should aim for. So, for example, maybe single letter variables would be fine.

Agreed. This is just a helper DSL. Full functionality is always available by directly making Julia functions.  I am aiming for to cover what's common and not too difficult, but not going to cover everything.

**Comment by zahachtah** [comment]
Not sure if this is the right place for this but:

I often need to define ode functions that combine scalar with vectors, is this possible and if so, would it be possible to reserve capital letters for vectors?

example, simple competition with optimal growth temperatures (Z):

```julia
f = @ode_def competition begin
    X'=r*(1-sum(X)) * exp(-(Z-temperature(t)).^2)-m
end Z=>linspace(0.0,40.0,100) r=>1.0 m=0.05
``` 
temperature(t) is a function that changes over time, and X is a vector of species biomasses in this case. 

i.e. this should expand into:

```julia
for i in 1:NumberOfSpecies
    dX[i]=r*(1-sum(X)) * exp(-(Z[i]-temperature(t)).^2)-m
end
```

May be better to use multiScaleModels?

**Comment by ChrisRackauckas** [comment]
I wonder if we should do some kind of multistep design, like JuMP?

`@ode_def` could turn into the macro for defining equation parts (maybe rename?). When it sees that some variable has a derivative, it makes it an independent variable. So the functionality from before for very simple models works and is still automatic.

But variables could also be declared. Example composing different ways:

```julia
m = DiffeqModel()
@add_variable m X 1:10
@add_parameter m Z linspace(0.0,40.0,100)
@eq_def m begin
    X'[i]=(r*(1-sum(X)) * exp(-(Z[i]-temperature(t)).^2)-m).*X[i]
end r=>1.0 m=0.05
```

Matching coefficients implies a loop. This would allow one to compose equations as well, like @tshort 's suggestion. `@ode_def` would just be a shorthand for a common form of this? It seems like we will need some internal form to do the computations, so this would just expose it up to an "advanced user" level.

**Comment by gabrielgellner** [comment]
I really like the JuMP style version. I like having a more explicit style like this as models get more complex, it feels far less magical as an end user.

**Comment by zahachtah** [comment]
If its not just a special case I also like it. Another question: assume I want to nest parametrised functions, could the root one import the parameters of the others?

e.g. 
```julia
type  growthA <: Function
   a::Float64
   b::Float64
end

type  growthB <: Function
   c::Float64
   d::Float64
end

(p::growthA)(t,u,du) = begin
    #someStuff
end

f1=growthA(0.1,0.2)
f2=growthB(0.3,0.4)

(p::growthB)(t,u,du) = begin
    #someStuff
end

@ode_def change begin
    x=f1(t,u,du)+f2(t,u,du)
end
```

and when the ```@ode_def``` macro runs it will automagically add ```a=>0.1, b=>0.2, c=>0.3, d=>0.4``` and pass them to the functions inside.

And also, Hi Gabriel @gabrielgellner , nice to see theoretical ecologist here, are you in the same department as Colleen Webb? She's a good friend of mine.

**Comment by zahachtah** [comment]
or even:

```julia

FunctionToUse=growthA

@ode_def change begin
    x=F(t,u,du)
end F=> FunctionToUse
```

**Comment by gabrielgellner** [comment]
@zahachtah Small world! Yes I am a post doc with Colleen. She is the best.

**Comment by ChrisRackauckas** [comment]
@zahachtah I think allowing it to put together types and parameters like that would be difficult, but allowing one to build the model iteratively in the JuMP style would allow this. You could `@add_variable` one by one. We probably need a syntax for "adding equations", like 

```
@eq_def m begin
    X_t = ...
end
@eq_def m begin
    @append X_t = ... # adds this to the previous statement
end
```

I have no idea how that would work though if we allow DAEs though! Find the same LHS?

**Comment by zahachtah** [comment]
Was just a thought. I can solve it in other ways too. DiffEquations is already ridiculously good and convinient compared to anything else.

**Comment by ChrisRackauckas** [comment]
Well it's a good idea. I'll see if someone else has a thought for if it's possible to implement.

**Comment by ChrisRackauckas** [comment]
Since right now all of the API issues are being fixed due to the upcoming workshop: this is the sole remaining possible API change which will not be able to be addressed (this will take quite a lot of work). Should we just initiate the deprecation of `dx` to `x_t` now, even without the rest of it (with a depwarn)? Or should we just accept both for now?

**Comment by zahachtah** [comment]
Whatever is easiest for you.

**Comment by ChrisRackauckas** [comment]
They're all pretty much the same to implement. I just want users to be happy with the API.

**Comment by matthieugomez** [comment]
I would be interested in a nice syntax to write PDE too.
I need it for a package focused on HJBS.
For now, I am using NamedTuples
https://github.com/matthieugomez/EconPDEs.jl

**Comment by ChrisRackauckas** [comment]
I am thinking that the engine to support this will need to be different. Right now it does a simple find-replace to build a function. That is good for what it does in this constrained syntax, but it can't do much more.

I think that, to aim for a DifferentialEquations 2.0 release in the next week or so to solidify everything with good time before the workshop, I will take a two-pronged approach here. I will finish off some of the remaining issues in ParameterizedFunctions.jl and consider `@ode_def` "done", and then make a separate DiffEqDSL.jl to build a much more expressive domain-specific language and not have it interfere with `@ode_def` (since it already works just fine, so might as well not break it!). There we can create an underlying type-structure that can handle the proposed framework, and a set of macros for that. That will not be done any time soon (it will take awhile), so I think this is a good solution.

What I will be finishing up here is:

1) Giving an alternative to use the `x_t` syntax with `@ode_def` (but keep `dx`)
2) Try to fix https://github.com/JuliaDiffEq/ParameterizedFunctions.jl/issues/12, https://github.com/JuliaDiffEq/ParameterizedFunctions.jl/issues/11, and https://github.com/JuliaDiffEq/ParameterizedFunctions.jl/issues/20. Other issues will be considered in the scope of the new project, and this will go into a stable bug-fixing and maintenance mode. I hope to do this by the end of the week and call this part of 2.0.

**Comment by ChrisRackauckas** [comment]
Thanks for all of your comments! Going with the DiffEqDSL.jl idea, let's take the discussion over to https://github.com/JuliaDiffEq/DiffEqDSL.jl/issues/1 .
