### ISSUE TITLE
ParameterizedFunctions: Coding an ODE with noise in the measurement function

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/ParameterizedFunctions.jl#25]
How to code the Lorenz problem with the data generation code inside the problem such that the Signal to Noise Ratio (SNR) is an additional  parameter to be estimated.

g1 = @ode_def_nohes LorenzExample begin
dx = σ*(y-x)
dy = x*(ρ-z) - y
dz = x*(y) - β*z
end σ=>10.0 ρ=>28.0 β=>2.66667 # Parameters used to construct the dataset

r0 = [0.1; 0.0; 0.0] # Initial values of the system in space
tspan = (0.0, 4.0)
prob = ODEProblem(g1, r0, tspan)

#snr => [0.05]  

data_sol = solve(prob,Vern7(),saveat=t,reltol=1e-12,abstol=1e-12)
data = vecarr_to_arr(data_sol)
data .+= snr.*randn(size(data))          # Noise added to signal from ODE system as required

The parameter estimation should check that 'snr' is the 'observed' value built in the data. A coding for snr => 0.05 similar to σ=>10.0 ρ=>28.0 and β=>2.66667

**Comment by ChrisRackauckas** [comment]
Use an SDE?

**Comment by finmod** [comment]
Sorry. Is this the one? http://docs.juliadiffeq.org/latest/tutorials/sde_example.html

**Comment by ChrisRackauckas** [comment]
Yes. But it depends on what you're trying to do. If you're trying to put in system noise, then that's what you need. If you just want observational noise, then you'd be adding noise afterwards. But observational noise doesn't truly make sense in the diffeq, so there shouldn't be a parameter for it unless it's treated like an algebraic variable with a random relation. 

SNR has to be determined differently anyways.

**Comment by finmod** [comment]
This appears to answer the question. I apologize for now keeping abreast with JuliaDiffDocs.

f = @ode_def_nohes LorenzSDE begin
  dx = σ*(y-x)
  dy = x*(ρ-z) - y
  dz = x*y - β*z
end σ=>10. ρ=>28. β=>2.66

g = @ode_def_nohes LorenzSDENoise begin
  dx = α
  dy = α
  dz = α
end α=>3.0

prob_sde_lorenz = SDEProblem(f,g,[1.0,0.0,0.0],(0.0,10.0))
sol = solve(prob_sde_lorenz)
plot(sol,vars=(1,2,3))

**Comment by ChrisRackauckas** [comment]
Just not that's not observational noise, rather it's system noise.
