### ISSUE TITLE
Providing @ode_def with input parameters defined in a separate file

### ISSUE THREAD

**Issue by ivborissov** [JuliaDiffEq/ParameterizedFunctions.jl#28]
It will be useful to have an option to provide input parameters for the ODE system defined via @ode_def through separate file like:

pf = @ode_def Test begin
...
end init_params.txt

and init_params can contain parameters defined via inlining or =>
a=2
b=3
c=>5
..
etc

**Comment by ChrisRackauckas** [comment]
Would it make more sense to read in the whole definition from a file?

**Comment by ivborissov** [comment]
Sorry, didn't get the idea

**Comment by ChrisRackauckas** [comment]
`pf = read("climate_model.diffeq")` which defines the diffeq and parameters in similar syntax to the macro, but allows it to be in a file and gives freedom to write parameters like that?

**Comment by ivborissov** [comment]
Yes, exactly

**Comment by ivborissov** [comment]
In follow up to this idea. Basically an ODE problem can consist of 3 parts: initial parameters values, varaibles and functions definitions and system of odes itself. I think it might be nice to have an option to define those parts in separate files

**Comment by ChrisRackauckas** [comment]
Yeah, I don't have anything against it, it's just about finding the time to write the functionality to do this. I think the quickest implementation, one which would work quite well, would be to read the file into a string and parse it into the form for the `@ode_def` call, and then just use that.

**Comment by ChrisRackauckas** [comment]
The values are no longer in the `@ode_def` itself, so this should be much easier to handle (just pass them to `ODEProblem`).
