### ISSUE TITLE
ParameterizedFunction not exported?

### ISSUE THREAD

**Issue by zahachtah** [JuliaDiffEq/ParameterizedFunctions.jl#31]
```ParameterizedFunctions.ParameterizedFunction(pf_func,[1.5,1.0])```

works

but not 

```ParameterizedFunction(pf_func,[1.5,1.0])```

**Comment by ChrisRackauckas** [comment]
It's in DiffEqBase. That's because the name for this package no longer works well... you should think of this package as "ode_def macro .jl" since that's all that is native to this. But since we can't easily change package names, it's stuck with the name from however long ago.

**Comment by zahachtah** [comment]
ok, so its 

```using DiffEqBase, DifferntialEquations```
 to get all of those goodies?

**Comment by ChrisRackauckas** [comment]
well, `using DifferentialEquations` alone should give all of the goodies. `using DiffEqBase` will specifically give everything related to the interface like the problem definitions and `ParameterizedFunction`.

**Comment by zahachtah** [comment]
of course, my mistake, me working late, should go to bed....

unneccessary issue, feel free to delete :-D closing
