### ISSUE TITLE
Direct use of ode_def_opts(name::Symbol,opts,ex::Expr,params)

### ISSUE THREAD

**Issue by MatthieuDartiailh** [JuliaDiffEq/ParameterizedFunctions.jl#49]
Hi,

I am trying to use `ode_def_opts` directly rather than the different provided macros. Rather than trying to customize the options as suggested in your README, I want to circumvent the lack of intermediate calculation by doing expressions manipulation (replacing a long subexpression using interpolation) and passing the resulting expression to `ode_def_opts`. I tried the very simple following example:

```julia
opts = Dict{Symbol,Bool}(
           :build_tgrad => true,
           :build_jac => true,
           :build_expjac => false,
           :build_invjac => false,
           :build_invW => false,
           :build_hes => false,
           :build_invhes => false,
       :build_dpfuncs => true)

eval(ode_def_opts(:FF, opts, :(df = 0.1*f)))
```

But the eval fails (see the end of the post). Since I am new to Julia I guess, I am misunderstanding something about macro evaluation, since the following works:

```julia
@ode_def(FF, :(df = 0.1*f))
```

I looked at the macroexpansion of `@ode_def(FF, :(df = 0.1*f))` and it is indeed different from what I get from `ode_def_opts(:FF, opts, :(df = 0.1*f))` but I do not know how to go from one to the other.

I am running on Julia 1.1 and a freshly installed ParameterizedFunctions package.

Evaluation error:
ERROR: syntax: invalid syntax (escape (block (method #0=(outerref FF)) (block (method FF (call (core svec) (call (core svec) (call (core Typeof) #0#)) (call (core svec))) (lambda (#self#) (((#self# #1=(core Any) 0) (#56 #1# 18) (#57 #1# 18) (#58 #1# 18) (#59 #1# 18)) () 0 ()) (block (line 72 /Users/mdartiailh/.julia/packages/ParameterizedFunctions/ozDxQ/src/maketype.jl) (newvar #56) (newvar #57) (newvar #58) (newvar #59) (call (outerref FF) (block (null) (block (= #56 (new ##56#60)) (null) (unnecessary #56))) #2=(outerref nothing) (block (null) (block (= #57 (new ##57#61)) (null) (unnecessary #57))) (block (null) (block (= #58 (new ##58#62)) (null) (unnecessary #58))) #2# #2# (block (null) (block (= #59 (new ##59#63)) (null) (unnecessary #59))) #<julia: LinearAlgebra.UniformScaling{Bool}(λ=true)> #2# (copyast (inert (= df (call * #<julia: 0.1> f)))) #<julia: Array{Expr, (1,)}[Expr(:call, :*, 0.1, 1)]> #<julia: Array{Expr, (0,)}[]> #<julia: Array{Expr, (0,)}[]> #<julia: Array{Symbol, (0,)}[]> #<julia: Array{Any, (0, 0)}[]> #<julia: Array{Expr, (1,)}[Expr(:call, :*, 0, 1)]> (copyast (inert (block (= (ref internal_var___grad 1) (call * 0 1)) (null)))) (copyast (inert (block (null)))) (copyast (inert (call error #<julia: "Exponential Jacobian Does Not Exist">))) (copyast (inert (block (null)))) (copyast (inert (call error #<julia: "Inverse Jacobian Does Not Exist">))) (copyast (inert (call error #<julia: "Inverse Rosenbrock-W Does Not Exist">))) (copyast (inert (call error #<julia: "Inverse Rosenbrock-W Transformed Does Not Exist">))) (copyast (inert (call error #<julia: "Hessian Does Not Exist">))) (copyast (inert (call error #<julia: "Inverse Hessian Does Not Exist">))) (copyast (inert (= df (call * #<julia: 0.1> f) (null)))) (copyast (inert (= df (call * #<julia: 0.1> f)))) (copyast (inert (= df (call * #<julia: 0.1> f)))) (copyast (inert (= df (call * #<julia: 0.1> f) (call hcat)))) #<julia: Array{Symbol, (0,)}[]>))))) (unnecessary #0#)))

**Comment by ChrisRackauckas** [comment]
Yeah working at this level is very difficult since `eval` works in the global scope. DiffEqWebServer uses it though and gets around it by evaling everything else it needs (and it used a much much older version), but I wouldn't recommend going this route. I'll close this as a "won't fix" since the real solution is to use ModelingToolkit.jl instead for this kind of work, but if you want to keep discussing feel free.

**Comment by MatthieuDartiailh** [comment]
Thanks for the pointer ! I will give a look at ModellingToolkit.jl, I must have missed it. Do you have more docs for it than the README ?

**Comment by ChrisRackauckas** [comment]
Not yet. It's still too new and in development, but being used in some projects.

**Comment by MatthieuDartiailh** [comment]
Ok I will ask questions over at this repo if an encounter any difficulty I cannot work around.
