### ISSUE TITLE
Field Wfact

### ISSUE THREAD

**Issue by dlill** [JuliaDiffEq/ParameterizedFunctions.jl#54]
Dear JuliaDiffEq-Team,

thanks for all the great work you are doing! It's really fun to work your packages! Here is an error I just encountered, I guess it has to do with a recent renaming of `invW` into `Wfact` in DiffEqBase

```julia
myode =  @ode_def begin
    dX = -k*X
end k

myprob = ODEProblem(myode, ones(1), 1., ones(1))
solve(myprob, Rosenbrock23())
```

Best, Daniel

**Comment by ChrisRackauckas** [comment]
I think you just got incompatible versions somehow. Try updating again and it should work. I just tried with the releases and it worked fine. Let me know if it doesn't work out.

**Comment by dlill** [comment]
Thanks, that fixed it
