### ISSUE TITLE
Running parameter estimation example from DiffEqDocs

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/ParameterizedFunctions.jl#7]
using ParameterizedFunction in the Lotka-Volterra example gives the following error:

LoadError: ArgumentError: Module ParameterizedFunction not found in current path.
Run `Pkg.add("ParameterizedFunction")` to install the ParameterizedFunction package.
while loading In[1], in expression starting on line 1

 in require(::Symbol) at .\loading.jl:365

Then Pkg.add("ParameterizedFunction") gives:
ERROR: unknown package ParameterizedFunction

**Comment by ChrisRackauckas** [comment]
`using ParameterizedFunctions`. You forgot the `s`. Julia packages which are built around a type pluralize the type's name.

**Comment by ChrisRackauckas** [comment]
Note that ParameterizedFunctions.jl should be automatically setup when `using DifferentialEquations` in the newest version.

**Comment by finmod** [comment]
Subtle! The s was missing twice in the .md page. Coming to grammar and as a Frenchman, I have strong feelings about "tableaus". It should be "tableaux".

Anyway, after correction and Pkg.update(), the outcome remains the same:

using DifferentialEquations, ParameterizedFunctions

f = @ode_def_nohes LotkaVolterraTest begin
  dx = a*x - b*x*y
  dy = -c*y + d*x*y
end a=>1.5 b=1.0 c=3.0 d=1.0

u0 = [1.0;1.0]
tspan = [0;10.0]
prob = ODEProblem(f,u0)

LoadError: MethodError: no method matching DiffEqBase.ODEProblem{uType,tType,isinplace,F}(::ParameterizedFunctions.LotkaVolterraTest, ::Array{Float64,1})
Closest candidates are:
  DiffEqBase.ODEProblem{uType,tType,isinplace,F}(::Any, ::Any, !Matched::Any) at C:\Users\Denis\.julia\v0.5\DiffEqBase\src\problems/ode_problems.jl:15
  DiffEqBase.ODEProblem{uType,tType,isinplace,F}{T}(::Any) at sysimg.jl:53
while loading In[5], in expression starting on line 8

**Comment by ChrisRackauckas** [comment]
I see, it's still on the old syntax. I pushed updated docs. It should update whenever Travis gets to it.

**Comment by ChrisRackauckas** [comment]
Sensitivity analysis will also update.

**Comment by finmod** [comment]
parameter estimation is now fine. Thank you for this major staring point for me.

**Comment by finmod** [comment]
For sensitivity, I run: 

using DifferentialEquations, ParameterizedFunctions

f = @ode_def_nohes LotkaVolterra begin
  dx = a*x - b*x*y
  dy = -c*y + d*x*y
end a=>1.5 b=>1 c=>3 d=1

prob = ODELocalSensitivityProblem(f,[1.0;1.0],(0.0,10.0))

and it gives the following error:

LoadError: invalid redefinition of constant LotkaVolterra
while loading In[2], in expression starting on line 69

 in #maketype#6(::Expr, ::Array{SymEngine.Basic,1}, ::Expr, ::Array{SymEngine.Basic,2}, ::Expr, ::Array{SymEngine.Basic,2}, ::Expr, ::Array{SymEngine.Basic,2}, ::Expr, ::Expr, ::Expr, ::Array{SymEngine.Basic,1}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Expr, ::Expr, ::Array{Symbol,1}, ::Array{Expr,1}, ::Array{Expr,1}, ::Array{SymEngine.Basic,2}, ::Expr, ::ParameterizedFunctions.#maketype, ::Symbol, ::DataStructures.OrderedDict{Symbol,Any}, ::Expr, ::Array{Expr,1}, ::Array{Symbol,1}, ::Expr) at C:\Users\Denis\.julia\v0.5\ParameterizedFunctions\src\maketype.jl:24
 in (::ParameterizedFunctions.#kw##maketype)(::Array{Any,1}, ::ParameterizedFunctions.#maketype, ::Symbol, ::DataStructures.OrderedDict{Symbol,Any}, ::Expr, ::Array{Expr,1}, ::Array{Symbol,1}, ::Expr) at .\<missing>:0
 in #ode_def_opts#1(::UniformScaling{Int64}, ::Symbol, ::Function, ::Symbol, ::Dict{Symbol,Bool}, ::Expr, ::Expr, ::Vararg{Expr,N}) at C:\Users\Denis\.julia\v0.5\ParameterizedFunctions\src\ode_def_opts.jl:226
 in ode_def_opts(::Symbol, ::Dict{Symbol,Bool}, ::Expr, ::Expr, ::Vararg{Expr,N}) at C:\Users\Denis\.julia\v0.5\ParameterizedFunctions\src\ode_def_opts.jl:5

and two dirty packages after update: DiffEqDocs and DiffEqTutorials

**Comment by ChrisRackauckas** [comment]
No problem. I'll be adding some tie-ins to JuliaML soon once I figure that out. These commands are still pretty basic, but since it shows how to "plug into" 3 different optimization packages, the source code should be pretty clear for how to link others from the source code (if you want to take a stab at JuMP, that would be cool! Though it may need its own package because it would pull in a huge dependency, so it would have to be isolated a bit).

**Comment by ChrisRackauckas** [comment]
```julia
using DifferentialEquations, ParameterizedFunctions

f = @ode_def_nohes LotkaVolterra begin
dx = ax - bxy
dy = -cy + dxy
end a=>1.5 b=>1 c=>3 d=1

prob = ODELocalSensitivityProblem(f,[1.0;1.0],(0.0,10.0))

and it gives the following error:

LoadError: invalid redefinition of constant LotkaVolterra
while loading In[2], in expression starting on line 69

in #maketype#6(::Expr, ::Array{SymEngine.Basic,1}, ::Expr, ::Array{SymEngine.Basic,2}, ::Expr, ::Array{SymEngine.Basic,2}, ::Expr, ::Array{SymEngine.Basic,2}, ::Expr, ::Expr, ::Expr, ::Array{SymEngine.Basic,1}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Expr, ::Expr, ::Array{Symbol,1}, ::Array{Expr,1}, ::Array{Expr,1}, ::Array{SymEngine.Basic,2}, ::Expr, ::ParameterizedFunctions.#maketype, ::Symbol, ::DataStructures.OrderedDict{Symbol,Any}, ::Expr, ::Array{Expr,1}, ::Array{Symbol,1}, ::Expr) at C:\Users\Denis.julia\v0.5\ParameterizedFunctions\src\maketype.jl:24
in (::ParameterizedFunctions.#kw##maketype)(::Array{Any,1}, ::ParameterizedFunctions.#maketype, ::Symbol, ::DataStructures.OrderedDict{Symbol,Any}, ::Expr, ::Array{Expr,1}, ::Array{Symbol,1}, ::Expr) at .<missing>:0
in #ode_def_opts#1(::UniformScaling{Int64}, ::Symbol, ::Function, ::Symbol, ::Dict{Symbol,Bool}, ::Expr, ::Expr, ::Vararg{Expr,N}) at C:\Users\Denis.julia\v0.5\ParameterizedFunctions\src\ode_def_opts.jl:226
in ode_def_opts(::Symbol, ::Dict{Symbol,Bool}, ::Expr, ::Expr, ::Vararg{Expr,N}) at C:\Users\Denis.julia\v0.5\ParameterizedFunctions\src\ode_def_opts.jl:5
```

That's just because DiffEqProblemLibrary already defines the same `LotkaVolterra` model. I just sent a fix for the docs to make it:

```julia
f = @ode_def_nohes LotkaVolterraSensitivity begin
  dx = a*x - b*x*y
  dy = -c*y + d*x*y
end a=>1.5 b=>1 c=>3 d=1
```

since it'll be good to show in the docs the full workflow.

**Comment by ChrisRackauckas** [comment]
>and two dirty packages after update: DiffEqDocs and DiffEqTutorials

You shouldn't have to clone the docs (unless you're editing them to contribute). For the tutorials, I'll ask on Discourse for a good solution to this.

**Comment by ChrisRackauckas** [comment]
Note that you can always un-dirty a package with `git stash` to get rid of your local changes, but there should be a more user friendly way of handling this. Could you please open an issue about this on DiffEqTutorials?

**Comment by finmod** [comment]
The LotkaVolterraSensitivity patch is working:
f = @ode_def_nohes LotkaVolterraSensitivity begin
  dx = a*x - b*x*y
  dy = -c*y + d*x*y
end a=>1.5 b=>1 c=>3 d=1

Now at:

x = vecvec_to_mat([sol[i][1:sol.prob.numvars] for i in 1:length(sol)])

We get:
LoadError: type ODELocalSensitivityProblem has no field numvars
while loading In[4], in expression starting on line 1

 in collect(::Base.Generator{UnitRange{Int64},##1#2}) at .\array.jl:307

**Comment by ChrisRackauckas** [comment]
Make that `sol.prob.indvars`. Note that example is following the tests from here:

https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/blob/master/test/runtests.jl

The tests tell me when things need to update to API changes. I wish the docs did.

**Comment by finmod** [comment]
Spot on after adding all the using....achieved identical graph. Thanks

**Comment by ChrisRackauckas** [comment]
Alright, this one is done. BTW, thanks for checking through all the docs! It's hard to make sure it's all updated without going line-by-line like this!
