### ISSUE TITLE
Running parameterized functions

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/ParameterizedFunctions.jl#8]
Onto parameterized functions.md, at

g = LotkaVolterra(a=0.3,b=20.3)

I get:

LoadError: InexactError()
while loading In[5], in expression starting on line 1

 in ParameterizedFunctions.LotkaVolterra(::Expr, ::Array{Expr,1}, ::Array{SymEngine.Basic,1}, ::Array{Expr,1}, ::Array{Expr,1}, ::Array{Symbol,1}, ::Array{SymEngine.Basic,1}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Expr, ::Expr, ::Expr, ::Expr, ::Expr, ::Expr, ::Expr, ::Expr, ::Expr, ::Expr, ::Expr, ::Array{Symbol,1}, ::Float64, ::Float64, ::Int64) at C:\Users\Denis\.julia\v0.5\ParameterizedFunctions\src\maketype.jl:25
 in #LotkaVolterra#14(::Expr, ::Array{Expr,1}, ::Array{SymEngine.Basic,1}, ::Array{Expr,1}, ::Array{Expr,1}, ::Array{Symbol,1}, ::Array{SymEngine.Basic,1}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Array{SymEngine.Basic,2}, ::Expr, ::Expr, ::Expr, ::Expr, ::Expr, ::Expr, ::Expr, ::Expr, ::Expr, ::Expr, ::Expr, ::Array{Symbol,1}, ::Float64, ::Float64, ::Int64, ::Type{T}) at C:\Users\Denis\.julia\v0.5\ParameterizedFunctions\src\maketype.jl:72
 in (::Core.#kw#Type)(::Array{Any,1}, ::Type{ParameterizedFunctions.LotkaVolterra}) at .\<missing>:0

**Comment by ChrisRackauckas** [comment]
Oops. The parameters in the example were written as ints. They were changed to floats.

**Comment by finmod** [comment]
This one is ok. Further down:
f  = @fem_def (x) begin
  sin(α.*x).*cos(α.*y)
end α=>2π
gD = @fem_def (x) begin
  sin(α.*x).*cos(α.*y)/β
end α=>2π β=>8π*π

gives:

LoadError: MethodError: Cannot `convert` an object of type Int64 to an object of type Expr
This may have arisen from a call to the constructor Expr(...),
since type constructors fall back to convert methods.
while loading In[12], in expression starting on line 1

**Comment by ChrisRackauckas** [comment]
I just put in an update for the docs. It required a bug fix on ParameterizedFunctions.jl which was just pushed to master.

**Comment by ChrisRackauckas** [comment]
Closed due to that bug fix.
